# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 32009b1ce8052ef48df35ec5343f93eef0d56ff60a57e0cfce79a8ac5b32c47e2c3bb580204a1fa3f6123863077ffcee84b7520a5b642d6eef37f5e441fc65d0

test:
  secret_key_base: 134e0c77f5e0bfc39bf0f79f665621e8ca685d6ae26051d2ea0046029e85434ce004dfd3ad8ea2a6e233d9139a84e62b54a7c5502867b22ef7d4f900032780c2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
